# Generated by Django 5.0.3 on 2024-03-26 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('review', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('discount', models.IntegerField(blank=True, max_length=2, null=True)),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('sizes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='graceapi.size')),
            ],
        ),
    ]
