# Generated by Django 5.0.3 on 2024-03-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graceapi', '0003_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='slug',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
