# Generated by Django 5.0.3 on 2024-04-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graceapi', '0004_size_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='back_img',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='front_img',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
    ]
